### ISSUE TITLE
Use Tailwind CSS color classes

### ISSUE THREAD

**Issue by larrasu** [yisibell/nuxt-svg-icons#1]
Is it possible to use Tailwind CSS color classes for the `fill` or `stroke` attribute? I tried adding a class to the component but it doesn't work.

Amazing work by the way! Thank you for this module.

**Comment by yisibell** [comment]
>

**Comment by yisibell** [comment]
> Is it possible to use Tailwind CSS color classes for the `fill` or `stroke` attribute? I tried adding a class to the component but it doesn't work.
> 
> Amazing work by the way! Thank you for this module.

Of course, just set `fill` or `stroke` as `currentColor`, and then use **tailwindcss colors** util. and it will work fine.

Thank you for using!

**Comment by larrasu** [comment]
Hello, thanks for the reply! I forgot Tailwind has `fill-{color}` classes.
