### ISSUE TITLE
Feature Request: stroke-width

### ISSUE THREAD

**Issue by luigigorlero** [yisibell/nuxt-svg-icons#2]
Hello! Thank you for this.
I was wondering if you were considering adding a parameter to control paths’ `stroke-width` for monoline icons

**Comment by yisibell** [comment]
> Hello! Thank you for this. I was wondering if you were considering adding a parameter to control paths’ `stroke-width` for monoline icons

In version `1.16.0`, the `stroke-width` attribute is now supported.
